<?
require_once('config.php');
require_once('system/core.php');
require_once('system/db.php');
require_once('system/common.php');
require_once('system/render.php');
require_once('system/admin.php');
require_once('system/jdf.php');
require_once('system/env.php');
session_start();
